version: "3.6"
services:
  blackbox_db:
    container_name: blackbox_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    image: "postgres:11-alpine"
    restart: always
    volumes:
      - postgres_blackbox:/var/lib/postgresql/data/
  blackbox:
    hostname: blackbox
    command: mix phx.server
    restart: unless-stopped
    build: .
    depends_on:
      - blackbox_db
    env_file:
      - .env
    ports:
      - "4000:4000"
    volumes:
      - .:/app
volumes:
  postgres_blackbox:
